- name: Create EDEN Computers
  community.windows.win_domain_ou:
    name: EDEN Computers
    state: present
  register: init_eden_computers_ou

- name: Create EDEN Users
  community.windows.win_domain_ou:
    name: EDEN Users
    state: present
  register: init_eden_users_ou

- name: Create reverse lookup zone
  community.windows.win_dns_zone:
    name: 50.168.192.in-addr.arpa
    replication: forest
    type: primary
    state: present
  async: 120
  poll: 5

# The second execution is needed because otherwise the variable only contains 'path' value and not 'ou'
- name: Poll EDEN Computers
  community.windows.win_domain_ou:
    name: EDEN Computers
    state: present
  register: eden_computers_ou

- name: Poll EDEN Users
  community.windows.win_domain_ou:
    name: EDEN Users
    state: present
  register: eden_users_ou

- name: Redirect default computers
  win_shell: "redircmp '{{  eden_computers_ou['ou']['DistinguishedName']  }}'"
  when: init_eden_computers_ou.changed
  async: 120
  poll: 5
  
- name: Redirect default users
  win_shell: "redirusr '{{  eden_users_ou['ou']['DistinguishedName']  }}'"
  when: init_eden_users_ou.changed

- name: Create new domain admin
  community.windows.win_domain_user:
    name: radmin
    firstname: Remote
    surname: Administrator
    password: "{{ password }}"
    groups: 
      - Domain Admins
      - Enterprise Admins
  async: 120
  poll: 5