---
- name: Copy req file to Root CA
  win_copy:
    src: "/tmp/{{  sub_ca_hostname  }}.req"
    dest: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_hostname  }}.req"
- name: Check whether crt exists
  win_stat:
    path: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_crt_name  }}.crt"
  register: init_sub_crt
- name: Accept cert req
  win_shell: |
    Certreq.exe -Config "{{ root_ca_hostname }}\{{ root_ca_common_name }}" -Submit C:\Windows\System32\CertSrv\CertEnroll\{{ sub_ca_hostname }}.req
    certutil.exe -resubmit 3
    Certreq.exe -f -Config "{{ root_ca_hostname }}\{{ root_ca_common_name }}" -Retrieve 2 C:\Windows\System32\CertSrv\CertEnroll\{{ sub_ca_crt_name }}.crt
  when: not init_sub_crt.stat.exists
- name: Check whether crt exists after
  win_stat:
    path: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_crt_name  }}.crt"
  register: post_sub_crt
- name: Fetch Sub CA certificate
  fetch:
    src: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_crt_name  }}.crt"
    dest: "/tmp/{{  sub_ca_crt_name  }}.crt"
  when: post_sub_crt.stat.exists