---
- name: Copy req file to Root CA
  win_copy:
    src: "/tmp/{{  sub_ca_hostname  }}.req"
    dest: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_hostname  }}.req"
- name: Check whether req exists
  win_stat:
    path: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_crt_name  }}.req"
  register: init_sub_req
- name: Accept cert req
  win_shell: |
    [String]$RequestResult = Certreq.exe -Submit C:\Windows\System32\CertSrv\CertEnroll\{{ sub_ca_hostname }}.req
    $Matches = [Regex]::Match($RequestResult, 'RequestId:\s([0-9]*)')
    If ($Matches.Groups.Count -lt 2) {
      Throw 'Error getting Request ID from SubCA certificate submission.'
    }
    [int]$RequestId = $Matches.Groups[1].Value
    [String]$SubmitResult =  CertUtil.exe -Resubmit $RequestId
    If ($SubmitResult -notlike 'Certificate issued.*') {
      Throw 'Unexpected result issuing SubCA request.'
    }
    Certreq.exe -Retrieve $RequestId C:\Windows\System32\CertSrv\CertEnroll\{{ sub_ca_crt_name }}.crt
  when: not init_sub_req.stat.exists
- name: Check whether crt exists after
  win_stat:
    path: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_crt_name  }}.crt"
  register: post_sub_crt
- name: Fetch Sub CA certificate
  fetch:
    src: "C:\\Windows\\System32\\CertSrv\\CertEnroll\\{{  sub_ca_crt_name  }}.crt"
    dest: "/tmp/{{  sub_ca_crt_name  }}.crt"
  when: post_sub_crt.stat.exists