- name: Install Sub CA
  include_tasks: install_sub_ca.yml
  when: inventory_hostname == sub_ca_hostname
- name: Configure Sub CA
  include_tasks: config_sub_ca.yml
  when: inventory_hostname == sub_ca_hostname