---
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: kerberos, ntlm
domain: eden.local
domain_upper: EDEN.LOCAL
domain_dn: DC=EDEN, DC=LOCAL
netbios_domain: eden
initial_domain_admin: "administrator@{{  domain  }}"
domain_admin: "radmin@{{  domain  }}"
