---
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: kerberos, ntlm
domain: eden.local
domain_upper: EDEN.LOCAL
domain_dn: DC=EDEN, DC=LOCAL
netbios_domain: eden
initial_domain_admin: "administrator@{{  domain  }}"
domain_admin: "radmin@{{  domain  }}"
root_ca_name: EDEN-ROOT-CA
root_ca_common_name: "{{  domain  }}-Root-CA"
root_ca_crt_name: "{{  root_ca_name  }}_{{  domain  }}-Root-CA"
sub_ca_name: EDEN-CA-01
sub_ca_common_name: "{{ domain }}-Issuing-CA"
sub_ca_crt_name: "{{  sub_ca_name  }}_{{  domain  }}-Issuing-CA"