---
- hosts: "{{ rdc_hostname }}"
  vars:
    ansible_host: "{{ rdc_hostname }}"
    pdc_ip: "{{ hostvars[pdc_hostname]['ansible_host'] }}"
    rdc_ip: "{{ hostvars[rdc_hostname]['ansible_host'] }}"
  roles: 
  - replica_domain_controller